name: Update list

on:
  workflow_dispatch:
  schedule:
  - cron:  '*/15 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install Dependencies
      run: pnpm i

    - name: Download Files
      run: node ./download.js
      
    - name: Merge Files
      run: node ./merge.js

    - name: Run utilites
      run: node ./util.js

    - name: Create branch
      run: git checkout -b list
      
    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
       add: 'ultralist.txt'
       author_name: 'updater'
       author_email: 'admin@boofdev.eu'
       message: 'Updated list'
       push: '--set-upstream origin list'
