name: Update list

on:
  workflow_dispatch:
  schedule:
  - cron:  '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    #- name: Use Node.js
     # uses: actions/setup-node@v2
      #with:
       # node-version: '20'

    #- name: Install pnpm
      #run: npm install -g pnpm

    #- name: Install Dependencies
      #run: pnpm i

    #- name: Download Files
      #run: node ./download.js
      
    #- name: Merge Files
      #run: node ./merge.js

    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'

    - name: Merge with SHM
      run: java -jar simple_hosts_merger.jar allowlists.txt blocklists.txt ./lists/ultralist cache;
      
    - name: Commit
      uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
       add: '.'
       author_name: 'updater'
       author_email: 'admin@boofdev.eu'
       message: 'Updated list'
